version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress/.
      dockerfile: Dockerfile
      args:
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
        - DB_ROOT_PASSWORD
        - WP_URL
    env_file:
      - .env
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
    networks:
      - inception
    restart: always
  mariadb:
    build:
      context: requirements/mariadb/.
      dockerfile: Dockerfile
      args:
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
        - DB_HOST
        - WP_URL
        - WP_ADMIN
        - WP_ADMIN_PASSWORD
        - WP_ADMIN_EMAIL
    env_file:
      - .env
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge
